# Generated by Django 4.1.7 on 2023-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
